package common

const (
	PuzzleEndpoint        = "puzzle"
	EchoPuzzleEndpoint    = "echopuzzle"
	SiteVerifyEndpoint    = "siteverify"
	VerifyEndpoint        = "verify"
	LoginEndpoint         = "login"
	TwoFactorEndpoint     = "2fa"
	ResendEndpoint        = "resend"
	ErrorEndpoint         = "error"
	RegisterEndpoint      = "signup"
	ExpiredEndpoint       = "expired"
	SettingsEndpoint      = "settings"
	LogoutEndpoint        = "logout"
	PropertyEndpoint      = "property"
	PropertiesEndpoint    = "properties"
	OrgEndpoint           = "org"
	OrganizationsEndpoint = "orgs"
	DashboardEndpoint     = "dashboard"
	NewEndpoint           = "new"
	StatsEndpoint         = "stats"
	TabEndpoint           = "tab"
	ReportsEndpoint       = "reports"
	IntegrationsEndpoint  = "integrations"
	EditEndpoint          = "edit"
	DeleteEndpoint        = "delete"
	MembersEndpoint       = "members"
	GeneralEndpoint       = "general"
	EmailEndpoint         = "email"
	UserEndpoint          = "user"
	APIKeysEndpoint       = "apikeys"
	UsageEndpoint         = "usage"
	ReadyEndpoint         = "ready"
	LiveEndpoint          = "live"
	MoveEndpoint          = "move"
	NotificationEndpoint  = "notification"
	SelfHostedEndpoint    = "selfhosted"
	ActivationEndpoint    = "activation"
	AuditLogsEndpoint     = "auditlogs"
	EventsEndpoint        = "events"
	ExportEndpoint        = "export"
	AsyncTaskEndpoint     = "asynctask"
)
